services:
  mongo:
    image: mongo:latest
    container_name: mongo-library
    restart: always
    command: ["mongod", "--bind_ip_all"]
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: library
    volumes:
      - mongo_library_data:/data/db

volumes:
  mongo_library_data:
